Update CI (#76)

diff --git a/.github/workflows/pypi.yaml b/.github/workflows/pypi.yaml
--- a/.github/workflows/pypi.yaml
+++ b/.github/workflows/pypi.yaml
@@ -5,62 +5,74 @@ on:
     types:
       - published
   workflow_dispatch:
+  push:
+    branches:
+      - main
 jobs:
-  test-deploy:
+  build-artifacts:
+    runs-on: ubuntu-latest
     if: github.repository == 'NCAR/ncar-jobqueue'
-    runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v3
         with:
-          python-version: '3.x'
+          fetch-depth: 0
+      - uses: actions/setup-python@v3
+        name: Install Python
+        with:
+          python-version: 3.8
+
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           python -m pip install setuptools setuptools-scm wheel twine check-manifest
       - name: Build tarball and wheels
         run: |
-          python setup.py sdist bdist_wheel
-          python -m pip wheel . -w dist --no-deps
-      - name: Test the artifacts
+          git clean -xdf
+          git restore -SW .
+          python -m build --sdist --wheel .
+      - name: Check built artifacts
         run: |
           python -m twine check dist/*
-
-      - name: Publish package to TestPyPI
-        uses: pypa/gh-action-pypi-publish@v1.5.0
+          pwd
+          if [ -f dist/ncar-jobqueue-0.0.0.tar.gz ]; then
+            echo "❌ INVALID VERSION NUMBER"
+            exit 1
+          else
+            echo "✅ Looks good"
+          fi
+      - uses: actions/upload-artifact@v2
         with:
-          user: __token__
-          password: ${{ secrets.TESTPYPI_PASSWORD }}
-          repository_url: https://test.pypi.org/legacy/
-          verbose: true
+          name: releases
+          path: dist
 
-  deploy:
-    needs: test-deploy
-    if: startsWith(github.ref, 'refs/tags')
+  test-built-dist:
+    needs: build-artifacts
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v3
+      - uses: actions/setup-python@v3
+        name: Install Python
         with:
-          python-version: '3.x'
-      - name: Install dependencies
+          python-version: 3.8
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
+      - name: List contents of built dist
         run: |
-          python -m pip install --upgrade pip
-          python -m pip install setuptools setuptools-scm wheel twine check-manifest
-      - name: Build tarball and wheels
-        run: |
-          python setup.py sdist bdist_wheel
-          python -m pip wheel . -w dist --no-deps
-      - name: Test the artifacts
-        run: |
-          python -m twine check dist/*
-
+          ls -ltrh
+          ls -ltrh dist
+  upload-to-pypi:
+    needs: test-built-dist
+    if: github.event_name == 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/download-artifact@v2
+        with:
+          name: releases
+          path: dist
       - name: Publish package to PyPI
         uses: pypa/gh-action-pypi-publish@v1.5.0
         with:
-          user: ${{ secrets.PYPI_USERNAME }}
+          user: __token__
           password: ${{ secrets.PYPI_PASSWORD }}
-          skip_existing: true
           verbose: true
